name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            media_source_manager.py
          body: |
            ## What's New
            - Bug fixes and improvements
            
            ## Installation
            1. Download `media_source_manager.py`
            2. In OBS, go to **Tools → Scripts**
            3. Click the **+** button and select the downloaded script
            
            ## Requirements
            - OBS Studio 28.0 or later
            - Python 3.6+
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
